name: apolopay_sdk
description: Apolo Pay SDK for Flutter.
version: 1.0.0
homepage: https://www.apolopay.app
repository: https://github.com/ApoloPay/payment-button-sdk
issue_tracker: https://github.com/ApoloPay/payment-button-sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  socket_io_client: ^3.1.4
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
